package by.jwd.cafe.command;

public final class SessionAttribute {
    public static final String ALL_SHEETS_SESSION = "all_sheets_ses";
    public static final String BALANCE_SESSION = "balance_ses";
    public static final String BALANCE_DATA_SESSION = "balance_data_ses";
    public static final String CART = "cart";
    public static final String CART_SUM = "cart_sum";
    public static final String CHANGE_PASSWORD_RESULT = "change_password_result";
    public static final String CURRENT_PAGE = "current_page";
    public static final String CURRENT_BALANCE = "current_balance";
    public static final String CURRENT_LOYALTY_POINTS = "current_loyalty_points";
    public static final String CURRENT_ROLE = "current_role";
    public static final String CURRENT_LOGIN_SESSION = "current_login_ses";
    public static final String CURRENT_USER_ID = "current_user_id";
    public static final String CURRENT_USER_IS_ACTIVE = "current_user_is_active";
    public static final String CURRENT_SHEET_SESSION = "current_sheet_ses";
    public static final String FIRST_ID_SESSION = "first_id_ses";
    public static final String LAST_ID_SESSION = "last_id_ses";
    public static final String EMAIL_SESSION = "email_ses";
    public static final String IS_ACTIVE_SESSION = "is_active_ses";
    public static final String LOCALE = "locale";
    public static final String LOGIN_SESSION = "login_ses";
    public static final String LOYALTY_POINTS_SESSION = "loyalty_points_ses";
    public static final String MENU_ITEM_NAME_SESSION = "menu_item_name_ses";
    public static final String MESSAGE_ITEM_ADDED_TO_CART = "message_item_added_to_cart";
    public static final String MENU_ITEM_DESCRIPTION_SESSION = "menu_description_name_ses";
    public static final String MENU_ITEM_PRICE_SESSION = "menu_item_price_ses";
    public static final String MENU_ITEM_AVAILABLE_SESSION = "menu_item_available_ses";
    public static final String MENU_ITEM_PICTURE_SESSION = "menu_item_picture_ses";
    public static final String NEW_EMAIL_SESSION = "new_email_ses";
    public static final String NEW_PASSWORD_SESSION = "new_password_ses";
    public static final String NOT_FOUND_SESSION = "not_found_ses";
    public static final String FIRST_NAME_SESSION = "first_name_ses";
    public static final String LAST_NAME_SESSION = "last_name_ses";
    public static final String MIN_PICK_UP_TIME = "min_pick_up_time";
    public static final String MAX_PICK_UP_TIME = "man_pick_up_time";
    public static final String ORDER_DATA_SESSION = "order_data_ses";
    public static final String ORDER_CONFIRMED_MESSAGE = "order_confirmed_message";
    public static final String PASSWORD_SESSION = "password_ses";
    public static final String PAGINATION_SESSION = "pagination_ses";
    public static final String PAYMENT_TYPE_SESSION = "payment_type_ses";
    public static final String PICK_UP_TIME_SESSION = "pick_up_time_ses";
    public static final String POINTS_FOR_ACCOUNT = "points_for_account";
    public static final String POINTS_FOR_CASH = "points_for_cash";
    public static final String REPEAT_PASSWORD_SESSION = "repeat_password_ses";
    public static final String REFILL_BALANCE_RESULT = "refill_balance_result";
    public static final String REFILL_AMOUNT_SESSION = "refill_amount_ses";
    public static final String REGISTRATION_RESULT = "registration_result";
    public static final String ROLE_NAME_SESSION = "role_name_ses";
    public static final String UPDATE_PERSONAL_DATA_RESULT = "update_personal_data_result";
    public static final String UPDATE_USER_STATUS_RESULT = "update_user_status_result";
    public static final String USER_ID_SESSION = "user_id_ses";
    public static final String USER_DATA_SESSION = "user_data_ses";
    public static final String WRONG_AMOUNT_OVERSIZE_SESSION = "wrong_amount_oversize_ses";
    public static final String WRONG_AMOUNT_SESSION = "wrong_amount_ses";
    public static final String WRONG_EMAIL_SESSION = "wrong_email_ses";
    public static final String WRONG_EMAIL_EXISTS_SESSION = "wrong_email_exists_ses";
    public static final String WRONG_LOGIN_OR_PASSWORD_SESSION = "wrong_login_or_password_ses";
    public static final String WRONG_LOGIN_SESSION = "wrong_login_ses";
    public static final String WRONG_LOGIN_EXISTS_SESSION = "wrong_login_exists_ses";
    public static final String WRONG_FIRST_NAME_SESSION = "wrong_first_name_ses";
    public static final String WRONG_LAST_NAME_SESSION = "wrong_last_name_ses";
    public static final String WRONG_PASSWORD_SESSION = "wrong_password_ses";
    public static final String WRONG_NEW_PASSWORD_SESSION = "wrong_new_password_ses";
    public static final String WRONG_OLD_PASSWORD_SESSION = "wrong_old_password_ses";
    public static final String MISMATCH_PASSWORDS_SESSION = "mismatch_passwords_ses";
    public static final String WRONG_MENU_ITEM_NAME = "wrong_menu_item_name";
    public static final String WRONG_MENU_ITEM_DESCRIPTION = "wrong_menu_item_description";
    public static final String WRONG_MENU_ITEM_PRICE = "wrong_menu_item_price";

    private SessionAttribute() {
    }
}
